server:
  port: ${PORT:9000}

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver