server:
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    layout: BaseLayout
    operationsSorter: alpha
    disable-swagger-default-url: false
    path: /v1/api-docs